"""add_embedding_column_to_paints

Revision ID: 40be0420a4a7
Revises: 5dbdcd2557ef
Create Date: 2025-10-01 03:41:40.334598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40be0420a4a7'
down_revision: Union[str, None] = '5dbdcd2557ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paints', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paints', 'embedding')
    # ### end Alembic commands ###
