"""add_paint_tables

Revision ID: a421b53964c8
Revises: 22b917409d64
Create Date: 2025-09-30 22:24:15.314358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a421b53964c8'
down_revision: Union[str, None] = '22b917409d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paints',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('surface_types', sa.ARRAY(postgresql.ENUM('ALVENARIA', 'MADEIRA', 'FERRO', 'CONCRETE', 'METAL', 'PLASTIC', name='surfacetype')), nullable=False),
    sa.Column('environment', postgresql.ENUM('INTERNO', 'EXTERNO', 'INTERNO_EXTERNO', name='environment'), nullable=False),
    sa.Column('finish_type', postgresql.ENUM('FOSCO', 'ACETINADO', 'BRILHANTE', 'SEMI_BRILHANTE', name='finishtype'), nullable=False),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('line', postgresql.ENUM('PREMIUM', 'STANDARD', 'ECONOMIC', name='paintline'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paints_color'), 'paints', ['color'], unique=False)
    op.create_index('ix_paints_color_surface', 'paints', ['color', 'surface_types'], unique=False)
    op.create_index(op.f('ix_paints_environment'), 'paints', ['environment'], unique=False)
    op.create_index('ix_paints_environment_line', 'paints', ['environment', 'line'], unique=False)
    op.create_index('ix_paints_features_gin', 'paints', ['features'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_paints_finish_type'), 'paints', ['finish_type'], unique=False)
    op.create_index(op.f('ix_paints_id'), 'paints', ['id'], unique=False)
    op.create_index(op.f('ix_paints_line'), 'paints', ['line'], unique=False)
    op.create_index(op.f('ix_paints_name'), 'paints', ['name'], unique=False)
    op.create_index('ix_paints_name_active', 'paints', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_paints_surface_types_gin', 'paints', ['surface_types'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paints_surface_types_gin', table_name='paints', postgresql_using='gin')
    op.drop_index('ix_paints_name_active', table_name='paints', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_paints_name'), table_name='paints')
    op.drop_index(op.f('ix_paints_line'), table_name='paints')
    op.drop_index(op.f('ix_paints_id'), table_name='paints')
    op.drop_index(op.f('ix_paints_finish_type'), table_name='paints')
    op.drop_index('ix_paints_features_gin', table_name='paints', postgresql_using='gin')
    op.drop_index('ix_paints_environment_line', table_name='paints')
    op.drop_index(op.f('ix_paints_environment'), table_name='paints')
    op.drop_index('ix_paints_color_surface', table_name='paints')
    op.drop_index(op.f('ix_paints_color'), table_name='paints')
    op.drop_table('paints')
    # ### end Alembic commands ###
