"""increase_image_url_field_size

Revision ID: c29c00c1cc91
Revises: 40be0420a4a7
Create Date: 2025-10-01 19:37:20.366347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29c00c1cc91'
down_revision: Union[str, None] = '40be0420a4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'image_url',
                    existing_type=sa.String(length=500),
                    type_=sa.Text(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'image_url',
                    existing_type=sa.Text(),
                    type_=sa.String(length=500),
                    existing_nullable=True)
    # ### end Alembic commands ###
